### ISSUE TITLE
Make our product talk to server

### ISSUE THREAD

**Issue by EmilyTav** [department-of-veterans-affairs/healthcare-application#15]

**Comment by awong-dev** [comment]
This is effectively taking the fields, finishing the `HealthApp.build1010ezXml` function, and then adding an iframe that does a post to the VOA endpoint at `https://www.voa.aac.va.gov/voa-ui/VOASubmit?inputXML=` (no clue if we need that get parameter).

We currently have no method of receiving a reply.  There are 2 routes for fixing this.  (1) We can make their team insert a CORS header on the endpoint allowing vets.gov to receive the reply. (2) We reverse engineer the weblogic endpoint and see if there's a way to have a callback URL back into vets.gov that could then notify our the javascript on our app.

The second method is preferred. I believe they are likely using standard weblogic connectors which I bet have a callback url wired in...but I don't actually know weblogic so this would be a little java research.
