### ISSUE TITLE
SocSec# validation broken

### ISSUE THREAD

**Issue by joduinn** [department-of-veterans-affairs/healthcare-application#169]
Found during tonight's preparations for tomorrow's big testing event. Summary is: 
- 9 digits no dash -> error message and unable to proceed  
- 9 digits two dashes -> error message and unable to proceed
- 9 digits ​_one_​ dash -> no error message, able to proceed

Here's some screenshots to demonstrate. 
<img width="536" alt="screen shot 2016-06-22 at 11 58 54 pm" src="https://cloud.githubusercontent.com/assets/714805/16291492/952e7ad0-38d5-11e6-89a1-20c5d171a90b.png">
<img width="536" alt="screen shot 2016-06-22 at 11 59 36 pm" src="https://cloud.githubusercontent.com/assets/714805/16291491/952db6a4-38d5-11e6-980f-33d10fc1fdaa.png">
<img width="526" alt="screen shot 2016-06-22 at 11 59 47 pm" src="https://cloud.githubusercontent.com/assets/714805/16291494/95327a0e-38d5-11e6-9fa3-e8360257f36e.png">

**Comment by austin-martinez** [comment]
this looks like it is because the social security number itself is invalid in our validations, not necessarily the formatting. we should probably update this function to just strip the dashes before validating as the question says the user can enter without dashes

```
function isValidSSN(value) {
  if (value === '123456789' || value === '123-45-6789') {
    return false;
```
