### ISSUE TITLE
When data entry fields are blank or have errors, the "continue" button should be visibly disabled

### ISSUE THREAD

**Issue by joduinn** [department-of-veterans-affairs/healthcare-application#170]
While trying to understand socsec# validation, as part of filing #169 , I noticed that the "Continue" button at the bottom of the form always appeared to be enabled. 

Current behaviour: when invalid socsec# entered, and an error message is being displayed, the "Continue" button remained blue, so it looked like I could ignore the error and click continue. In my case, the field with the error (and the error message) had scrolled off the top of the screen, so after some futile clicking on "continue", I decided to scroll up - just in case! Note: this will be worse on tiny-screen computers  like smartphones!

Expected behavior: when invalid socsec# entered, and an error message is being displayed, the "Continue" button should be grayed-out, so humans know they cannot expect to click on it.

**Comment by joduinn** [comment]
Pushing to @akainic for now, so it doesnt get lost, but please reassign and/or prioritize as you think best.

**Comment by akainic** [comment]
Moving this ticket to vets-website: https://github.com/department-of-veterans-affairs/vets-website/issues/4086
