### ISSUE TITLE
Improve app configuration

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/healthcare-application#208]
Right now, the Ansible scripts that deploy the healthcare app do a regex search/replace in `config.js` to configure the app for each deployment environment, which is rather fragile. Looking around, it looks like the `nconf` package provides a cleaner solution:

http://stackoverflow.com/questions/5869216/how-to-store-node-js-deployment-settings-configuration-files

Would it be possible to integrate this package into the healthcare app? For reference, this is what we're doing right now:

The replacement code lives here:

https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/vetsgov/healthcare-app/tasks/main.yml#L63

And takes values from here:

https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/vetsgov/healthcare-app/defaults/main.yml#L12

At @ShawnArnwine's suggestion, including @alexose.

**Comment by alexose** [comment]
Excellent!  I would love to replace our existing config scripts.

`nconf` seems like a good solution here.  Rather than overwriting config.js, we could pass the relevant values via environment variables or command line arguments.  Potentially sensitive settings would still live in the devops repo.  Is this what you had in mind?

(It would also be easy to accomplish this with native node, but I agree that `nconf` looks cleaner.)

**Comment by ghost** [comment]
Yeah, both environment-specific and sensitive settings would reside in the devops repo (probably with defaults appropriate for running a local dev copy). It would be nice if the `healthcare-application` repo just had a blank `config.json`, and did something like `nconf.file({ file: 'config.json' });`. That way, Ansible could just overwrite `config.json` with the appropriate values.

**Comment by alexose** [comment]
It seems like the problem that the regexes solve is that `devops` doesn't want to duplicate all of the configuration options in `healthcare-application`, but still wants to be able to override them.  So yeah, I'll make the application check for the existence of a `config.json`, which will extend whatever is in `config.js`.

Hopefully that makes sense!  PR incoming...

**Comment by alexose** [comment]
@mechaxl #209 is merged.  Changing over the regexes next.

**Comment by alexose** [comment]
Blocked on getting AWS credentials so I can test ansible.  Hopefully should have that cleared up soon

**Comment by ShawnArnwine** [comment]
What other AWS creds do you need?

**Comment by alexose** [comment]
Just needed an aws key/secret.  @mechaxl hooked me up.

Running into a different problem now:

```
ERROR! the role 'common-roles/process' was not found in /Users/alexose/devops/ansible/roles:/Users/alexose/devops/ansible:/etc/ansible/roles:/Users/alexose/devops/ansible/roles/vetsgov

The error appears to have been in '/Users/alexose/devops/ansible/roles/vetsgov/healthcare-app/meta/main.yml': line 12, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    become_user: root
  - role: common-roles/process
    ^ here
```

**Comment by ShawnArnwine** [comment]
@alexose did you get the ^^ resolved?

**Comment by alexose** [comment]
Yes I did!  Turns out you need to install submodules as well.
