### ISSUE TITLE
Pull requests from forks always fail on CI [discussion]

### ISSUE THREAD

**Issue by daguar** [department-of-veterans-affairs/healthcare-application#225]
Howdily doodily VA folks!

I opened a [tiny PR](https://github.com/department-of-veterans-affairs/healthcare-application/pull/222) to fix a typo in the README, and it failed CI twice, so I investigated a bit and found that current Travis + Sauce configuration will make CI always fail for external PRs (ie, a PR of a branch on a fork.)
### What's up

The [error](https://travis-ci.org/department-of-veterans-affairs/healthcare-application/builds/144274007#L860-L862) that pops up in CI is:

```
Sauce Labs Authentication Error.
You used username 'None' and access key 'None' to authenticate, which are not valid Sauce Labs credentials.
```

Digging, I found that Travis' Sauce [add-on page](https://docs.travis-ci.com/user/sauce-connect/) says:

> due to security restrictions, the Sauce Labs addon is not available on pull request builds.

They give a bit more detail [over here](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions):

> The most important restriction for pull requests is about secure environment variables and encrypted data.
> 
> A pull request sent from a fork of the upstream repository could be manipulated to expose any environment variables. The upstream repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone with a fork.
> 
> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.
> 
> Pull requests sent from forked repositories do not have access to encrypted variables or data.
### What to do?

First, I want to state up front my perception that the top priority of this project is (and should be!) making something that increases access for vets. Facilitating external contributions is (rightly) secondary to that goal. So if this slows/hurts progress towards the core goals, don't do it!

With that caveat, it seems like there are a few options to facilitate external PRs.
1. **Use/set up [Savage](https://github.com/twbs/savage) to allow PRs to be run with heightened permissions (SauceLabs cred access)**
   
   It looks like [this is how Bootstrap is running Sauce test suites](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#pull-request-bots) on external PRs. The trade-off is that there should probably be some security review to make sure there are no concerns there.
2. **Make SauceLabs tests only run on internal branches, and allow external branches to just be run using the other tests suites**
   
   Travis has a suggestion on how to do this [here](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions). The trade-off here is that cross-browser checks may not run, which may defeat the purpose of CI in some ways. (If you're using a continuous delivery process to automatically push builds, however, you could potentially do something like add a `production` branch and make the deployment run Sauce tests on `master` prior to merging + deploying into production.)
3. **Manually review PRs and make an internal copy of a PR branch if they don't present security risks**
   
   This is the most labor-intensive, but might be worth considering.

There may be other approaches I'm missing, but those are the ones I know of.

Anyway, let me know your thoughts when you have a spare minute, and congrats on the launch!

**Comment by leannammiller** [comment]
Thank you! This is part of a larger conversation about how to improve the ability for non-USDS folks to contribute to this project.

**Comment by J-Quag** [comment]
@markolson   / @ayaleloehr /  Can any of you review this? I'm not sure if this should be here.

**Comment by ayaleloehr** [comment]
This repo is no longer used as the code has moved to vets-api, so closing.
