### ISSUE TITLE
Resolve user bug report

### ISSUE THREAD

**Issue by earthboundkid** [department-of-veterans-affairs/healthcare-application#243]
https://github.com/department-of-veterans-affairs/vets-website/issues/2708

> I do not have an idea, but rather a comment to make about a feature. When the Healthcare application process moved to Vets.gov it was not available to those applying while on Active Duty. Then a short time later it showed up in an additional forms area. However that form is not working at the completion of the form and during the submission part. Once you check the "Confirm" box and send the form to the VA for processing you get the two boxes; the first one you click allow, the second you click yes, and then what used to happen is that an I.E. window would open and you would be presented with a Submission ID number indicating that your form was indeed received. Now, what happens is you get to the end, and then the I.E. window opens, but it just hangs and then reloops back to a Vets.gov page that does not fully load correctly. There is a short circuit in the submittal process.
> 
> http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/15630396-fix-the-1010ez-ad-form

**Comment by akainic** [comment]
We have had to remove the AD form from the landing page because it does not work. We will be changing the current form to accommodate future dates going forward.
