### ISSUE TITLE
Fix JSON-Schema Failures

### ISSUE THREAD

**Issue by markolson** [department-of-veterans-affairs/healthcare-application#256]
The most common form validation errors are:

Form Validation - ERROR keyword=pattern, dataPath=[object Object].email, schemaPath=#/properties/email/pattern, pattern=^(([a-zA-Z]|[0-9])|([-]|[_]|[.]))+[@](%28[a-zA-Z0-9]%29|%28[-]%29){2,63}[.](%28[a-zA-Z0-9]%29{2,63})+$, message=should match pattern "^(([a-zA-Z]|[0-9])|([-]|[_]|[.]))+[@](%28[a-zA-Z0-9]%29|%28[-]%29){2,63}[.](%28[a-zA-Z0-9]%29{2,63})+$"

Form Validation - ERROR keyword=format, dataPath=[object Object].lastEntryDate, schemaPath=#/definitions/date/format, format=date, message=should match format "date"

Form Validation - ERROR keyword=minLength, dataPath=[object Object].spouseAddress.street, schemaPath=#/definitions/address/properties/street/minLength, limit=1, message=should NOT be shorter than 1 characters, keyword=minLength, dataPath=[object Object].spouseAddress.city, schemaPath=#/definitions/address/properties/city/minLength, limit=1, message=should NOT be shorter than 1 characters

Form Validation - ERROR keyword=format, dataPath=[object Object].medicarePartAEffectiveDate, schemaPath=#/definitions/date/format, format=date, message=should match format "date"

**Comment by markolson** [comment]
The email failures were (hopefully) from the frontend and backend using different regexps to validate email addresses. The other 3 are going to need some investigation to see how we can trigger them, but the spouseAddress one is the next most common and may have to do with 'lives at the same address' logic.

**Comment by akainic** [comment]
@markolson trying to update this ticket and this is my understanding:

1. email failures have been fixed by aligning the frontend and backend regexs
2. spouseAddress one was fixed recently by @jbalboni 

The other 2 (2 and 4) sound like they still need to be addressed. They sound like the same issue. Reading the json schema docs I'm not sure where `format: "date"` comes from. I see only `datetime` in the docs. Not sure what format `date` is using exactly.

**Comment by markolson** [comment]
I think these are taken care of now. We haven't had errors like this in a while.

**Comment by leannammiller** [comment]
@markolson can you please confirm that this is done?
