### ISSUE TITLE
Update financial disclosure page language

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/healthcare-application#258]
Hey @akainic -- 

The content team created a word document to make edits to the financial disclosure page. 

Here are the edits that need to be made: 
[HCA.Financial.Disclosure_092916_approvedDSVA.docx](https://github.com/department-of-veterans-affairs/healthcare-application/files/505250/HCA.Financial.Disclosure_092916_approvedDSVA.docx)

Here's the issue if you need any content background: https://github.com/department-of-veterans-affairs/vets.gov-content/issues/52

Let me know if you have questions or need any clarification on anything!

**Comment by AnitraAppa** [comment]
Just updated https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/490

**Comment by akainic** [comment]
Going to close this ticket as this work is being covered by the ticket Anitra linked to above.
