### ISSUE TITLE
Remove10-10AD

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/healthcare-application#261]
Remove this 10-10AD  form https://www.vets.gov/healthcare/forms/1010ez-AD.pdf  since it does not work in any browser @akainic has tested and confirmed.

we will look at adding this field as an enhancement post november, but should be removed prior to Veterans Day since it does not currently work.

i believe we can then remove those odd instructions on the page as well since no forms will require that?  can we just have the CG pdf form on the page?  @crwallace 

we should clean up this page prior to Veterans Day since comms plan will highlight HCA and drive even more users to this page.

**Comment by koconnor719** [comment]
![screen shot 2016-10-18 at 6 23 07 pm](https://cloud.githubusercontent.com/assets/13770771/19498616/0155849c-9560-11e6-86f5-f7c152f627dd.png)

![Uploading Screen Shot 2016-10-18 at 6.24.10 PM.png…]()

**Comment by koconnor719** [comment]
moving to correct github (healthcare team).  sorry for mistake.

**Comment by akainic** [comment]
Closed by: https://github.com/department-of-veterans-affairs/vets-website/pull/3526
