### ISSUE TITLE
Add warning message with ES downtimes

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/healthcare-application#265]
Probably to the introduction page

**Comment by patrickvinograd** [comment]
I don't know if there's a best practice here, but it is definitely something that applies not just to HCA, but to all of the applications that touch any VA backend service. As such we might want to tackle it in a consistent way that doesn't require a commit to vets-website to add warning messages. It could be an additional API endpoint that serves per-backend downtime information, and then some sort of internal tool to let us add scheduled downtime info.

**Comment by akainic** [comment]
@patrickvinograd I like that idea. Would this enable us to add the warning message just during the times of scheduled maintenance? How much time do you think this would take us to implement?

**Comment by akainic** [comment]
@patrickvinograd wondering if you have an update here? We were just notified of downtime to ES on Saturday from 9 to 12, so we will have to implement something to take down HCA during that time. Wondering if we could start to think about what that might look like.

**Comment by leannammiller** [comment]
@akainic is this a @patrickvinograd card? can we estimate?

**Comment by akainic** [comment]
I think there are 2 things to do here:
1. Temporary solution for HCA for ~~Saturday~~ Sunday
2. Long-term solution for all applications

@patrickvinograd might be the best person to answer how (2) gets completed. I'm on (1) now.

**Comment by leannammiller** [comment]
@aub and @patrickvinograd will take this

**Comment by patrickvinograd** [comment]
Closing this in favor of https://github.com/department-of-veterans-affairs/vets.gov-team/issues/596
