### ISSUE TITLE
HCA serving wrong paths for several assets

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/healthcare-application#266]
Server logs indicate a bunch of mis-configured paths for various images/icons. This may be a byproduct of how HCA is now deployed, but we see 403s for these paths, all with a referrer somewhere under  `https://www.vets.gov/healthcare/apply/application/`:
- `GET /assets/images/design/icons/favicon.ico`
- `GET /assets/images/design/icons/apple-touch-icon-114x114.png`
- `GET /assets/images/design/icons/apple-touch-icon-72x72.png`
- `GET /assets/images/design/icons/apple-touch-icon.png`

Need to confirm whether those paths are correct with respect to how HCA is serving assets, and also probably ensure that there is a 'healthcare' prefix is the app itself is serving the assets vs. s3 serving the assets.

**Comment by akainic** [comment]
@patrickvinograd looking into this ticket finally. Those images all exist in the healthcare-application repo. Sounds like it's an issue of how they are being served? Perhaps @knkski can take a look?

**Comment by leannammiller** [comment]
to discuss at 12/12 sprint planning = @patrickvinograd

**Comment by leannammiller** [comment]
this may be resolved by the move to vets-api

**Comment by patrickvinograd** [comment]
I cannot reproduce this now - all these assets seem to load correctly. Closing - if we see missing assets after vets-api/vets-website consolidation, we can investigate then.
