### ISSUE TITLE
Readd E2E testing

### ISSUE THREAD

**Issue by knkski** [department-of-veterans-affairs/healthcare-application#303]
In the move from Travis to Jenkins (#301), some E2E testing bits were ripped out. We'll want to evaluate how best to add these back in. With HCA moving bit-by-bit to `vets-website` and `vets-api`, this may no longer be necessary, however.

**Comment by leannammiller** [comment]
can we confirm whether this is an issue still @knkski or @markolson

**Comment by knkski** [comment]
I think we can kick this can down the road and let it be subsumed by the `HCA` -> `vets-*` migration. @markolson, thoughts?

**Comment by leannammiller** [comment]
@markolson and @knkski can you please provide guidance on this?

**Comment by knkski** [comment]
The tests have been re-added in the move to `vets-website`:

https://github.com/department-of-veterans-affairs/vets-website/blob/master/test/hca/00-required.e2e.spec.js
