### ISSUE TITLE
Verify Submissions with ES

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#313]
Work with Josh and send over our conformance test results as samples for him to run through to ensure that the libraries we're using are outputting conformance XML requests.

**Comment by markolson** [comment]
This will use the samples generated in https://github.com/department-of-veterans-affairs/vets-api/pull/660 as a starting point.

**Comment by leannammiller** [comment]
waiting for josh confirmation to close

**Comment by leannammiller** [comment]
@markolson do you want to close this one?
