### ISSUE TITLE
Unit tests: spouse address fields

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#318]
see https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/327

**Comment by J-Quag** [comment]
@jbalboni  @annekainicUSDS   Do either of you know what this specifically references? The HCA Repo is dead and gone.

**Comment by J-Quag** [comment]
@markolson / @jbalboni   Was ist das?

**Comment by jbalboni** [comment]
No idea.

**Comment by annekainicUSDS** [comment]
Closing as I think this is no longer relevant.
