### ISSUE TITLE
Validate birthday to not allow for certain military experience

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#319]
see https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/436

**Comment by annekainicUSDS** [comment]
Depending on when the person was born, it is impossible for them to have certain military experience. For example, if the person was born in 1980, they can't also have served in Vietnam. This to me seems like a lot of logic to build into the front-end for not a lot of lift. I would say this should be de-prioritized or even closed.

**Comment by J-Quag** [comment]
This does seem excessive. We'll be hooking up to eMIS eventually so I dont think this is really needed.  Making the exec decision to close this.
