### ISSUE TITLE
Minor: Autoscroll to invalid entry does not go to correct place for repeated fields?

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#321]
see https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/412

**Comment by leannammiller** [comment]
@jbalboni will assist

**Comment by J-Quag** [comment]
Scroll to where the page is. Look to see if this is not already fixed. 
Review page for array fields. Not related to validation errors. 
Think this should be fixed for the most part.
