### ISSUE TITLE
VA Benefits Information conditional logic

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#322]
In the original VOA form, If you're 50% to 100% disabled, you don't get prompted for "Are you compensable VA Service Connected 0% - 40%?:"

Similarly, if you are service connected 0%-40%, you don't get asked if you have a pension.

I think the first two questions are actually mutually exclusive cause I they are asking "on a scale of 0-100, how disable were you from being on active duty?"

The last one is another thing meant for determining if you need to input financial information....

Might want to double check the flow here.

see https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/397

**Comment by J-Quag** [comment]
Can't have all three or even more than 1 item at a time.
