### ISSUE TITLE
Look into removing babel-polyfi

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#325]
https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/304

**Comment by annekainicUSDS** [comment]
There was a reason we could remove babel-polyfill (another thing we are using makes it duplicative), but I can't remember the exact reason. Perhaps @jbalboni remembers?

**Comment by jbalboni** [comment]
We can close this one, I think. We do need the polyfill file and we made some changes recently to remove parts of it we don't need.

**Comment by J-Quag** [comment]
Thanks! Closing.
