### ISSUE TITLE
Print Functionality

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#330]
future enhancement; users need to be able to print out application. this will be helpful in case any issues w/ online submission and Veteran calls the call center--they can enroll immediately on phone--Veterans will want to have a printout of all the detailed info they just entered. also we have heard from user research (Frog) that Veterans maintain their records very carefully in dealing w/ VA.

**Comment by J-Quag** [comment]
@markolson  @lihanli   Is this something we can look at doing with PDF fill we're looking at?

**Comment by markolson** [comment]
Possibly? I think we'd hit a lot of possible edge cases that would make it overall easier to do this as a print stylesheet on the frontend, if that's still a thing you can do.

**Comment by J-Quag** [comment]
Looking at using the review and submit page to a certain look and feel to show what was submitted. 
Building another page that uses the data that we have. 
Mark wants to do this, really badly.

**Comment by J-Quag** [comment]
UX review needed first for printable format / confirmation page.
